import enum


class CaptchaType(enum.Enum):
    NONE = "NONE"
    RECAPTCHA = "RECAPTCHA"
    HCAPTCHA = "HCAPTCHA"
    TURNSTILE = "TURNSTILE"


class WriteType(enum.Enum):
    WEBAPI_THREADPOST = "WEBAPI_THREADPOST"
    WEBAPI_THREADWRITE = "WEBAPI_THREADWRITE"
    MONAZILLA_THREADPOST = "MONAZILLA_THREADPOST"
    MONAZILLA_THREADWRITE = "MONAZILLA_THREADWRITE"


class PluginVersion(enum.Enum):
    JAILBREAK = "JAILBREAK"  # Not used
    PIERROT = "PIERROT"
